### ISSUE TITLE
Fails Promise/A+ tests 2.0

### ISSUE THREAD

**Issue by sukima** [lazd/Pinky#2]
The latest promises-aplus-tests fail with master. I even converted the `test/pinky-adapter.js` to conform to the `deferred` adapter instead of the `pending` version. Still get over 400 specs that fail.

**Comment by lazd** [comment]
You're right, looking at 486 failures!

I've added a branch that exposes the correct adaptor API for 2.0 here:
https://github.com/lazd/Pinky/tree/tests2

It looks like the spec changed quite a bit in 1.1... Would gladly accept a PR to bring Pinky up-to-date, it may be some time before I can do it myself.

**Comment by lazd** [comment]
I got it passing [2.1](http://promises-aplus.github.io/promises-spec/#promise_states), [2.2](http://promises-aplus.github.io/promises-spec/#the__method), and [2.3.1](http://promises-aplus.github.io/promises-spec/#point-57) in the `tests2` branch with https://github.com/lazd/Pinky/commit/3fa90aecc8929828ef3e801fddd4e4a406f57b16.

@yonet said she'd take a look at getting [2.3.3](http://promises-aplus.github.io/promises-spec/#point-64) and [2.3.4](http://promises-aplus.github.io/promises-spec/#point-84) passing.

@yonet, can you make sure to write a comment that indicates the part of the spec your code? Currently, every comment that doesn't start with `// NEWSPEC` is an old comment with incorrect numbering.

**Comment by lazd** [comment]
Closed by 3ab54507521b907289b659d3364e54e0e97c67a8
